version: '3.8'

volumes:
  db-data:
    driver: local

services:
  app:
    build: ./docker/local/php-fpm
    container_name: app
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: db
    ports:
      - 3306:3306
    # パスワードで mysql にログインできるようにする
    command: --authentication_policy=mysql_native_password
    environment:
      - MYSQL_DATABASE=study_php
      - MYSQL_USER=default
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Tokyo
    volumes:
      - ./docker/local/mysql/init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
